CREATE TABLE DBUSER.BDP_TENANT (
    TENANT_ID   INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    TENANT      VARCHAR(64)  NOT NULL,
    TENANT_NAME VARCHAR(128) NOT NULL,
    SNOOZE_HR   INTEGER      NOT NULL WITH DEFAULT 2,
    PRIMARY KEY (TENANT_ID)
);

CREATE TABLE DBUSER.BDP_USER (
    USER_ID       INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    USER_NAME     VARCHAR(128) NOT NULL,
    USER_CONTACT_1 VARCHAR(256) NOT NULL,
    TENANT_ID     INTEGER      NOT NULL,
    USER_TIMES    INTEGER      NOT NULL WITH DEFAULT 3,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES DBUSER.BDP_TENANT(TENANT_ID)
);

CREATE TABLE DBUSER.BDP_HARDWARE (
    HARDWARE_UID    INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    HARDWARE_ID     VARCHAR(128) NOT NULL,
    HARDWARE_TYPE   VARCHAR(64)  NOT NULL,
    HARDWARE_DETAIL CLOB,
    TENANT_ID       INTEGER      NOT NULL,
    PRIMARY KEY (HARDWARE_UID),
    FOREIGN KEY (TENANT_ID) REFERENCES DBUSER.BDP_TENANT(TENANT_ID)
);

CREATE TABLE DBUSER.BDP_INCIDENT (
    INCIDENT_ID          INTEGER   NOT NULL GENERATED ALWAYS AS IDENTITY,
    INCIDENT_DETAIL      CLOB,
    INCIDENT_TIME        TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    INCIDENT_STATUS_CODE INTEGER   NOT NULL WITH DEFAULT 2,
    TENANT_ID            INTEGER   NOT NULL,
    CAUSE_HARDWARE       INTEGER   NOT NULL,
    INCIDENT_ID_ORIGINAL INTEGER,
    SNOOZE_TIME          TIMESTAMP,
    FIX_TIME             TIMESTAMP,
    NOTIFY_TIME          TIMESTAMP,
    PRIMARY KEY (INCIDENT_ID),
    FOREIGN KEY (TENANT_ID)      REFERENCES DBUSER.BDP_TENANT(TENANT_ID),
    FOREIGN KEY (CAUSE_HARDWARE) REFERENCES DBUSER.BDP_HARDWARE(HARDWARE_UID)
);

CREATE TABLE DBUSER.BDP_NOTIFICATION (
    NOTIFICATION_ID   VARCHAR(32)  NOT NULL,
    INCIDENT_ID       INTEGER      NOT NULL,
    NOTIFICATION_TYPE INTEGER      NOT NULL,
    NOTIFICATION_TIME TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    USER_ID           INTEGER      NOT NULL,
    RESPONSE          CLOB,
    PRIMARY KEY (NOTIFICATION_ID),
    FOREIGN KEY (INCIDENT_ID) REFERENCES DBUSER.BDP_INCIDENT(INCIDENT_ID),
    FOREIGN KEY (USER_ID)     REFERENCES DBUSER.BDP_USER(USER_ID)
);

CREATE TABLE DBUSER.BDP_RAW_EVENTS (
    EVENT_ID     INTEGER   NOT NULL GENERATED ALWAYS AS IDENTITY,
    READING_TIME TIMESTAMP NOT NULL,
    READING      CLOB      NOT NULL,
    HARDWARE_UID INTEGER   NOT NULL,
    PRIMARY KEY (EVENT_ID),
    FOREIGN KEY (HARDWARE_UID) REFERENCES DBUSER.BDP_HARDWARE(HARDWARE_UID)
);
