CREATE TABLE DBUSER.BDP_DBCHANGELOG (
    CHANGEID   VARCHAR(64)  NOT NULL,
    CHANGESET  VARCHAR(256) NOT NULL,
    APPLIED_AT TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (CHANGEID)
);
