CREATE TABLE DBUSER.BDP_TENANT (
    TENANT_ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    TENANT VARCHAR(100) not null UNIQUE ENFORCED, 
    TENANT_NAME VARCHAR(100) not null UNIQUE ENFORCED, 
    SNOOZE_HR INTEGER WITH DEFAULT 8, 
    ALARM_INTERVAL_HR INTEGER WITH DEFAULT 1, 
    PRIMARY KEY (TENANT_ID)) 
ORGANIZE BY ROW;

CREATE TABLE DBUSER.BDP_USER (
    USER_ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    TENANT_ID INTEGER not null, 
    USER_NAME VARCHAR(100) not null, 
    USER_CONTACT_1 VARCHAR(100) not null, 
    PRIMARY KEY (USER_ID), 
    UNIQUE (TENANT_ID, USER_CONTACT_1),
    FOREIGN KEY (TENANT_ID) REFERENCES DBUSER.BDP_TENANT (TENANT_ID))
ORGANIZE BY ROW;

CREATE TABLE DBUSER.BDP_USER_TIMES (
    USER_TIMES_CODE INTEGER not null UNIQUE ENFORCED,
    USER_TIMES_DETAIL VARCHAR(100), 
    PRIMARY KEY (USER_TIMES_CODE)
) ORGANIZE BY ROW;

INSERT INTO DBUSER.BDP_USER_TIMES (USER_TIMES_CODE, USER_TIMES_DETAIL)
   VALUES (1, 'WORKHOURS'), (2, 'EMERGENCY'), (3, 'ALL');

ALTER TABLE DBUSER.BDP_USER ADD COLUMN USER_TIMES INTEGER;

ALTER TABLE DBUSER.BDP_USER ADD FOREIGN KEY (USER_TIMES) REFERENCES DBUSER.BDP_USER_TIMES (USER_TIMES_CODE);
