CREATE TABLE DBUSER.BDP_TENANT (
    TENANT_ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    TENANT VARCHAR(100) not null UNIQUE ENFORCED, 
    TENANT_NAME VARCHAR(100) not null UNIQUE ENFORCED, 
    PRIMARY KEY (TENANT_ID)) 
ORGANIZE BY ROW;

CREATE TABLE DBUSER.BDP_USER (
    USER_ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    TENANT_ID INTEGER not null, 
    USER_NAME VARCHAR(100) not null, 
    USER_CONTACT_1 VARCHAR(100) not null, 
    PRIMARY KEY (USER_ID), 
    FOREIGN KEY (TENANT_ID) REFERENCES DBUSER.BDP_TENANT (TENANT_ID))
ORGANIZE BY ROW;
