CREATE TABLE DBUSER.BDP_HARDWARE (
    TENANT_ID INTEGER not null, 
    HARDWARE_ID VARCHAR(100) not null, 
    HARDWARE_TYPE VARCHAR(100), 
    HARDWARE_DETAIL VARCHAR(200), 
    FOREIGN KEY (TENANT_ID) REFERENCES DBUSER.BDP_TENANT (TENANT_ID)
) ORGANIZE BY ROW;


CREATE TABLE DBUSER.BDP_INCIDENT_STATUS (
    INCIDENT_STATUS_CODE INTEGER not null UNIQUE ENFORCED, 
    INCIDENT_STATUS_DETAIL VARCHAR(100), 
    PRIMARY KEY (INCIDENT_STATUS_CODE)
) ORGANIZE BY ROW;

CREATE TABLE DBUSER.BDP_INCIDENT (
    INCIDENT_ID VARCHAR(100) not null, 
    INCIDENT_DETAIL VARCHAR(1000) not null UNIQUE ENFORCED, 
    TENANT_ID INTEGER not null, 
    INCIDENT_TIME TIMESTAMP not null,
    INCIDENT_STATUS_CODE INTEGER not null,
    PRIMARY KEY (INCIDENT_ID), 
    FOREIGN KEY (TENANT_ID) REFERENCES DBUSER.BDP_TENANT (TENANT_ID),
    FOREIGN KEY (INCIDENT_STATUS_CODE) REFERENCES DBUSER.BDP_INCIDENT_STATUS (INCIDENT_STATUS_CODE)
) ORGANIZE BY ROW;

CREATE TABLE DBUSER.BDP_NOTIFICATION (
    NOTOFICATION_ID VARCHAR(100) not null, 
    INCIDENT_ID VARCHAR(100) not null, 
    RESPONSE VARCHAR(1000) not null, 
    NOTIFICATION_DETAIL VARCHAR(100) not null,
    NOTIFICATION_TIME TIMESTAMP not null,
    PRIMARY KEY (NOTOFICATION_ID), 
    FOREIGN KEY (INCIDENT_ID) REFERENCES DBUSER.BDP_INCIDENT (INCIDENT_ID)
) ORGANIZE BY ROW;
