CREATE TABLE DBUSER.BDP_HARDWARE (
    TENANT_ID INTEGER not null, 
    HARDWARE_ID VARCHAR(100) not null, 
    HARDWARE_TYPE VARCHAR(100), 
    HARDWARE_DETAIL VARCHAR(200), 
    FOREIGN KEY (TENANT_ID) REFERENCES DBUSER.BDP_TENANT (TENANT_ID)
) ORGANIZE BY ROW;


CREATE TABLE DBUSER.BDP_INCIDENT_STATUS (
    INCIDENT_STATUS_CODE INTEGER not null UNIQUE ENFORCED,
    INCIDENT_STATUS_DETAIL VARCHAR(100), 
    PRIMARY KEY (INCIDENT_STATUS_CODE)
) ORGANIZE BY ROW;

INSERT INTO DBUSER.BDP_INCIDENT_STATUS (INCIDENT_STATUS_CODE, INCIDENT_STATUS_DETAIL)
   VALUES (1, 'FIXED'), (2, 'ABNORMAL'), (3, 'SNOOZED');

CREATE TABLE DBUSER.BDP_NOTIFICATION_TYPE (
    NOTIFICATION_TYPE_CODE INTEGER not null UNIQUE ENFORCED,
    NOTIFICATION_TYPE_DETAIL VARCHAR(100), 
    PRIMARY KEY (NOTIFICATION_TYPE_CODE)
) ORGANIZE BY ROW;

INSERT INTO DBUSER.BDP_NOTIFICATION_TYPE (NOTIFICATION_TYPE_CODE, NOTIFICATION_TYPE_DETAIL)
   VALUES (1, 'ALARM'), (2, 'SNOOZE'), (3, 'FIX');

CREATE TABLE DBUSER.BDP_INCIDENT (
    INCIDENT_ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    INCIDENT_ID_ORIGINAL INTEGER, 
    INCIDENT_DETAIL VARCHAR(1000) not null, 
    TENANT_ID INTEGER not null, 
    INCIDENT_TIME TIMESTAMP not null,
    SNOOZE_TIME TIMESTAMP,
    NOTIFY_TIME TIMESTAMP,
    FIX_TIME TIMESTAMP,
    INCIDENT_STATUS_CODE INTEGER not null,
    PRIMARY KEY (INCIDENT_ID), 
    FOREIGN KEY (TENANT_ID) REFERENCES DBUSER.BDP_TENANT (TENANT_ID),
    FOREIGN KEY (INCIDENT_ID_ORIGINAL) REFERENCES DBUSER.BDP_INCIDENT (INCIDENT_ID),
    FOREIGN KEY (INCIDENT_STATUS_CODE) REFERENCES DBUSER.BDP_INCIDENT_STATUS (INCIDENT_STATUS_CODE)
) ORGANIZE BY ROW;

CREATE TABLE DBUSER.BDP_NOTIFICATION (
    NOTIFICATION_ID VARCHAR(100) not null, 
    INCIDENT_ID INTEGER not null, 
    USER_ID INTEGER not null, 
    RESPONSE VARCHAR(1000), 
    NOTIFICATION_DETAIL VARCHAR(100),
    NOTIFICATION_TYPE INTEGER not null,
    NOTIFICATION_TIME TIMESTAMP not null,
    PRIMARY KEY (NOTIFICATION_ID), 
    FOREIGN KEY (INCIDENT_ID) REFERENCES DBUSER.BDP_INCIDENT (INCIDENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES DBUSER.BDP_USER (USER_ID),
    FOREIGN KEY (NOTIFICATION_TYPE) REFERENCES DBUSER.BDP_NOTIFICATION_TYPE (NOTIFICATION_TYPE_CODE)
) ORGANIZE BY ROW;
