CREATE TABLE DBUSER.BDP_RAW_EVENTS(
    EVENT_ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    HARDWARE_UID INTEGER not null, 
    READING_TIME TIMESTAMP not null,
    READING VARCHAR(500), 
    FOREIGN KEY (HARDWARE_UID) REFERENCES DBUSER.BDP_HARDWARE (HARDWARE_UID)
) ORGANIZE BY ROW;

CREATE TABLE DBUSER.BDP_EVENTS(
    HARDWARE_UID INTEGER not null, 
    READING_TIME TIMESTAMP not null,
    READING VARCHAR(500), 
    FOREIGN KEY (HARDWARE_UID) REFERENCES DBUSER.BDP_HARDWARE (HARDWARE_UID)
) ORGANIZE BY ROW;
